apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: spring-k8s-efk-poc
build:
  artifacts:
  - image: spring-k8s-efk-poc
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
deploy:
  kubectl:
    manifests:
    - k8s/namespace.yml
    - k8s/service.yaml
    - k8s/deployment.yaml
