apiVersion: v1
kind: Service
metadata:
  namespace: spring-k8s-efk-poc
  name: spring-k8s-efk-poc
  labels:
    app: spring-k8s-efk-poc
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: spring-k8s-efk-poc
  type: ClusterIP
